### ISSUE TITLE
System.InvalidCastException:“指定的转换无效。”

### ISSUE THREAD

**Issue by pinzi** [TANZAME/Riz.XFramework#1]
数据能正常保存，但是却报错了，为什么呢？
`context.Insert<User>(new User()
                {
                    id = "2",
                    uname = "jame"
                });
                Console.WriteLine(context.GetTable<User>().Count());
                context.Insert<Product>(new Product()
                {
                    pname = "电视机",
                    price = 1900M
                });
                context.SubmitChanges();`

**Comment by TANZAME** [comment]
实体字段跟数据库字段没对应上
报错事务就回滚了，正常情况下数据是不能保存到数据库了

**Comment by TANZAME** [comment]
F
